type Mutation {
  commentRecomandationCreate(
    recommandationId: String!,
    contactId: String!
  ): Comment

  commentRecomandationUpdate(
  	recommandationId: String!,
    contactId: String!
  	): String!

  commentRecomandationDelete(
   recommandationId: String!
   ): String!
}
