type Query {
  contacts(filters: JSON, options: JSON): [Contact]
}

type Mutation {
  contactCreate(data: ContactCreateInput): Contact
  contactUpdate(contactId: String!, data: ContactCreateInput): Contact
}

input ContactCreateInput {
  familyName: String
  middleName: String
  givenName: String
  phoneNumbers: [PhoneNumberInput]
  company: String
  jobTitle: String
  emailAddresses: [EmailAddressesInput]
  hasThumbnail: Boolean
  thumbnailPath: String
  postalAddresses: [PostalAddressesInput]
  birthday: BirthdayInput
  tags: [String]
}

input PhoneNumberInput {
  label: String
  number: String
}

input EmailAddressesInput {
  label: String
  email: String
}

input PostalAddressesInput {
  street: String
  city: String
  state: String
  region: String
  postCode: String
  country: String
  label: String
}

input BirthdayInput {
  year: Float
  month: Float
  day: Float
}
